//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace 医院管理系统 {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class ds : DataSet {
        
        private _TableDataTable table_Table;
        
        public ds() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected ds(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Table"] != null)) {
                    this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public _TableDataTable _Table {
            get {
                return this.table_Table;
            }
        }
        
        public override DataSet Clone() {
            ds cln = ((ds)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Table"] != null)) {
                this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.table_Table = ((_TableDataTable)(this.Tables["Table"]));
            if ((this.table_Table != null)) {
                this.table_Table.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "ds";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/ds.xsd";
            this.Locale = new System.Globalization.CultureInfo("zh-CN");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.table_Table = new _TableDataTable();
            this.Tables.Add(this.table_Table);
        }
        
        private bool ShouldSerialize_Table() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void _TableRowChangeEventHandler(object sender, _TableRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn column挂号号码;
            
            private DataColumn column姓名;
            
            private DataColumn column年龄;
            
            private DataColumn column性别;
            
            private DataColumn column类型;
            
            private DataColumn column挂号费用;
            
            private DataColumn column病历;
            
            private DataColumn column地址;
            
            private DataColumn column日期;
            
            internal _TableDataTable() : 
                    base("Table") {
                this.InitClass();
            }
            
            internal _TableDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn 挂号号码Column {
                get {
                    return this.column挂号号码;
                }
            }
            
            internal DataColumn 姓名Column {
                get {
                    return this.column姓名;
                }
            }
            
            internal DataColumn 年龄Column {
                get {
                    return this.column年龄;
                }
            }
            
            internal DataColumn 性别Column {
                get {
                    return this.column性别;
                }
            }
            
            internal DataColumn 类型Column {
                get {
                    return this.column类型;
                }
            }
            
            internal DataColumn 挂号费用Column {
                get {
                    return this.column挂号费用;
                }
            }
            
            internal DataColumn 病历Column {
                get {
                    return this.column病历;
                }
            }
            
            internal DataColumn 地址Column {
                get {
                    return this.column地址;
                }
            }
            
            internal DataColumn 日期Column {
                get {
                    return this.column日期;
                }
            }
            
            public _TableRow this[int index] {
                get {
                    return ((_TableRow)(this.Rows[index]));
                }
            }
            
            public event _TableRowChangeEventHandler _TableRowChanged;
            
            public event _TableRowChangeEventHandler _TableRowChanging;
            
            public event _TableRowChangeEventHandler _TableRowDeleted;
            
            public event _TableRowChangeEventHandler _TableRowDeleting;
            
            public void Add_TableRow(_TableRow row) {
                this.Rows.Add(row);
            }
            
            public _TableRow Add_TableRow(string 姓名, string 年龄, string 性别, string 类型, string 挂号费用, string 病历, string 地址, System.DateTime 日期) {
                _TableRow row_TableRow = ((_TableRow)(this.NewRow()));
                row_TableRow.ItemArray = new object[] {
                        null,
                        姓名,
                        年龄,
                        性别,
                        类型,
                        挂号费用,
                        病历,
                        地址,
                        日期};
                this.Rows.Add(row_TableRow);
                return row_TableRow;
            }
            
            public _TableRow FindBy挂号号码(long 挂号号码) {
                return ((_TableRow)(this.Rows.Find(new object[] {
                            挂号号码})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                _TableDataTable cln = ((_TableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new _TableDataTable();
            }
            
            internal void InitVars() {
                this.column挂号号码 = this.Columns["挂号号码"];
                this.column姓名 = this.Columns["姓名"];
                this.column年龄 = this.Columns["年龄"];
                this.column性别 = this.Columns["性别"];
                this.column类型 = this.Columns["类型"];
                this.column挂号费用 = this.Columns["挂号费用"];
                this.column病历 = this.Columns["病历"];
                this.column地址 = this.Columns["地址"];
                this.column日期 = this.Columns["日期"];
            }
            
            private void InitClass() {
                this.column挂号号码 = new DataColumn("挂号号码", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column挂号号码);
                this.column姓名 = new DataColumn("姓名", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column姓名);
                this.column年龄 = new DataColumn("年龄", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column年龄);
                this.column性别 = new DataColumn("性别", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column性别);
                this.column类型 = new DataColumn("类型", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column类型);
                this.column挂号费用 = new DataColumn("挂号费用", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column挂号费用);
                this.column病历 = new DataColumn("病历", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column病历);
                this.column地址 = new DataColumn("地址", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column地址);
                this.column日期 = new DataColumn("日期", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column日期);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.column挂号号码}, true));
                this.column挂号号码.AutoIncrement = true;
                this.column挂号号码.AllowDBNull = false;
                this.column挂号号码.ReadOnly = true;
                this.column挂号号码.Unique = true;
            }
            
            public _TableRow New_TableRow() {
                return ((_TableRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new _TableRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(_TableRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this._TableRowChanged != null)) {
                    this._TableRowChanged(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this._TableRowChanging != null)) {
                    this._TableRowChanging(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this._TableRowDeleted != null)) {
                    this._TableRowDeleted(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this._TableRowDeleting != null)) {
                    this._TableRowDeleting(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            public void Remove_TableRow(_TableRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRow : DataRow {
            
            private _TableDataTable table_Table;
            
            internal _TableRow(DataRowBuilder rb) : 
                    base(rb) {
                this.table_Table = ((_TableDataTable)(this.Table));
            }
            
            public long 挂号号码 {
                get {
                    return ((long)(this[this.table_Table.挂号号码Column]));
                }
                set {
                    this[this.table_Table.挂号号码Column] = value;
                }
            }
            
            public string 姓名 {
                get {
                    try {
                        return ((string)(this[this.table_Table.姓名Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.姓名Column] = value;
                }
            }
            
            public string 年龄 {
                get {
                    try {
                        return ((string)(this[this.table_Table.年龄Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.年龄Column] = value;
                }
            }
            
            public string 性别 {
                get {
                    try {
                        return ((string)(this[this.table_Table.性别Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.性别Column] = value;
                }
            }
            
            public string 类型 {
                get {
                    try {
                        return ((string)(this[this.table_Table.类型Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.类型Column] = value;
                }
            }
            
            public string 挂号费用 {
                get {
                    try {
                        return ((string)(this[this.table_Table.挂号费用Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.挂号费用Column] = value;
                }
            }
            
            public string 病历 {
                get {
                    try {
                        return ((string)(this[this.table_Table.病历Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.病历Column] = value;
                }
            }
            
            public string 地址 {
                get {
                    try {
                        return ((string)(this[this.table_Table.地址Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.地址Column] = value;
                }
            }
            
            public System.DateTime 日期 {
                get {
                    try {
                        return ((System.DateTime)(this[this.table_Table.日期Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.table_Table.日期Column] = value;
                }
            }
            
            public bool Is姓名Null() {
                return this.IsNull(this.table_Table.姓名Column);
            }
            
            public void Set姓名Null() {
                this[this.table_Table.姓名Column] = System.Convert.DBNull;
            }
            
            public bool Is年龄Null() {
                return this.IsNull(this.table_Table.年龄Column);
            }
            
            public void Set年龄Null() {
                this[this.table_Table.年龄Column] = System.Convert.DBNull;
            }
            
            public bool Is性别Null() {
                return this.IsNull(this.table_Table.性别Column);
            }
            
            public void Set性别Null() {
                this[this.table_Table.性别Column] = System.Convert.DBNull;
            }
            
            public bool Is类型Null() {
                return this.IsNull(this.table_Table.类型Column);
            }
            
            public void Set类型Null() {
                this[this.table_Table.类型Column] = System.Convert.DBNull;
            }
            
            public bool Is挂号费用Null() {
                return this.IsNull(this.table_Table.挂号费用Column);
            }
            
            public void Set挂号费用Null() {
                this[this.table_Table.挂号费用Column] = System.Convert.DBNull;
            }
            
            public bool Is病历Null() {
                return this.IsNull(this.table_Table.病历Column);
            }
            
            public void Set病历Null() {
                this[this.table_Table.病历Column] = System.Convert.DBNull;
            }
            
            public bool Is地址Null() {
                return this.IsNull(this.table_Table.地址Column);
            }
            
            public void Set地址Null() {
                this[this.table_Table.地址Column] = System.Convert.DBNull;
            }
            
            public bool Is日期Null() {
                return this.IsNull(this.table_Table.日期Column);
            }
            
            public void Set日期Null() {
                this[this.table_Table.日期Column] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRowChangeEvent : EventArgs {
            
            private _TableRow eventRow;
            
            private DataRowAction eventAction;
            
            public _TableRowChangeEvent(_TableRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public _TableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
